### ISSUE TITLE
t[append/prepend] problem

### ISSUE THREAD

**Issue by atticushome** [aurelia/i18n#111] opened 2016-05-17 14:13 UTC
Hi!

If I use it like this `<label  t="[append]label"><input type="radio" model.bind="true" checked.bind="checked"></label>` checked.bind stops working.
Am I doing something wrong or is it not supposed to work like this?

Thanks!

**Comment by zewa666** [comment] 2016-05-18 07:13
Well ... yes its supposed to work, and no it does not do that currently :)
Tbh when this feature was designed that use-case wasn't kept in mind, so thanks for pointing that out.

**Comment by atticushome** [comment] 2016-05-18 07:15
Nice, thanks for a quick feedback.

**Comment by zewa666** [comment] 2016-06-02 06:54
@atticushome should be fixed with the latest commit, next Tuesday the new version should be available and ready to be tested

**Comment by EisenbergEffect** [comment] 2016-07-06 20:11
Closing since the fix was merged.

**Closed by EisenbergEffect** 2016-07-06 20:11 UTC
Labels: enhancement
