### ISSUE TITLE
Namespace issues

### ISSUE THREAD

**Issue by Souldrinker** [aurelia/i18n#85] opened 2016-03-29 10:49 UTC
I've just upgraded to aurelia-i18n 0.5.0 based on i18next v2 and have ran into some issues that I'm not sure if it's bugs, features or just me doing something wrong.

I changed my plugin setup to look like this (the commented out rows are for test and in earlier versions I only used the default namespace):
```
        .plugin("aurelia-i18n", instance => {
            instance.i18next.use(XHR);
            instance.setup({
                backend: {
                    loadPath: "locales/{{lng}}/{{ns}}.json"
                },
                lng: "en-AU"
                attributes: ["t", "i18n"],
                //ns: ["translation", "main"],
                //defaultNs: "main",
                fallbackLng: "en",
                debug: false
            });
```

The first issue I ran into was that if I set ```lng``` or ```fallbackLng``` to ```en``` the translation.json files never got loaded.

From what I can see that is because you in relativeTime.js set have this line:
```
this.service.i18next.addResources(key, 'translation', translation);
```
...which then in ```BackendConnector.queueLoad``` exclude the translation.json files to be loaded since hasResourceBundle returns true since the bundle already had been added in code.

I suppose this is intentional, but this prevents me from using the default translation namespace for my own translations (which wasn't the case in earlier versions).

I then tried to add the ns setup as suggested in your documentation, but realized that the syntax there where bad and should probably be as I commented out above.

But even then the defaultNS seem to be ignored, so if I uncomment the above and add ```main:``` to all my translations stuff seem to work.

I suppose that is also because you assume your resources already should exist to be able to use the different value converters?

Does this mean we always have to add namespace prefixes now with the new version?

**Comment by EisenbergEffect** [comment] 2016-03-29 11:03
@zewa666 Can you take a look at this?

**Comment by tuath** [comment] 2016-03-30 02:39
I think I have this same problem.

When running unbundled it works and I clearly see the backend provider initialized in the console. When running bundled (jspm bundle), then I don't see the backend get initialized and get a bunch of missing keys. When I inspect the i18n config, it looks fine. 

Very confused.

**Comment by zewa666** [comment] 2016-03-30 07:01
@Souldrinker can you prepare an example for me to take a look at?

**Comment by Souldrinker** [comment] 2016-03-30 11:32
@zewa666  Sorry for the delay, been busy with other stuff... But I pushed up a small sample based on the latest skeleton with some comments here: https://github.com/Souldrinker/i18next-test.

I'm not sure if it's intentional and it's no big issue if I now need to use custom namespaces, but it would be good to hear your thoughts of it.

I would have thought that if you passed in custom stuff you should do that under another another namespace than the default so people using this package could still keep using the default namespace without collisions, but...

**Comment by fmal** [comment] 2016-03-30 13:38
+1 I am having the exact same issue.

**Comment by zewa666** [comment] 2016-03-31 06:50
Thanks for the example @souldrinker. Quite busy this week as well over here, but will get to it by next week.

**Comment by johnraz** [comment] 2016-03-31 13:37
I do experience the same issue without bundling.

This is quite tricky to reproduce because i18next will load some resources or not depending on your settings.

You should be able to reproduce with the following (using XHR backend):
```
let config = {
  backend: {
    loadPath: '/locales/{{lng}}/{{ns}}.json'
  },

  attributes: ['t', 'i18n'],
  lng: 'en',
  fallbackLng : 'en',
  debug: true
};
```

Next try to activate, let's say french and you will get:

```
i18next: languageChanged fr
logger.js:25 i18next::translator: missingKey fr translation Username Username
logger.js:25 i18next::translator: missingKey fr translation Login Login
```

And I don't see any activity in the network panel, no 404 nothing, so it's not an issue with the resource not being available, i18next will simply not try to load the resource at all because it believes it is already loaded as per @Souldrinker's initial analysis.

Adding this line to the config file and renaming your translation files accordingly fixes it and then everything works as expected.:
```
ns: ['translation', 'anotherNs'],
```

**Comment by Jenselme** [comment] 2016-04-03 19:18
As mentioned in #86: I think I have the same issue with 0.5.0. I found a workaround: downgrade i18next 2.4.x to 2.3.5. From what I understand, 2.4.0 introduced a 10ms timeout before actually loading the resources that prevented aurelia-i18n to work properly.

I fixed my issue with PR #92

**Comment by shabalin** [comment] 2016-04-04 17:15
+1 

We have same issue, but only in bundled version of the app. I am not sure how does the bundling affect this behavior, but 
 Connector.prototype.queueLoad returns empty array since 
`store.hasResourceBundle(lng, ns)` condition is positive  because this "resource bundle" was already populated by relativeTime.js

**Comment by Souldrinker** [comment] 2016-04-07 08:49
Seems to be working fine now with v0.5.1 :-)

**Comment by zewa666** [comment] 2016-04-07 09:02
cool happy to hear that. Again thanks goes to @Jenselme for the fix :clap: 
Going to close this one, we can reopen if needed

**Comment by Souldrinker** [comment] 2016-04-07 09:02
Damn, I may have spoke to soon. It worked fine now until I bundled, but after bundling half of my application was in "en" (the langage I use in main.ts) and half in "sv-SE" (which I set in the activate method of my root view after fetching the user language from db).

I had this issue in earlier versions too until I set ```async: false```, but as far as I can see that option is no longer available? Any ideas?

**Closed by zewa666** 2016-04-07 09:02 UTC

**Comment by Souldrinker** [comment] 2016-04-07 10:00
Sorry, I didn't realize setLocale returned a promise. If I wait to resolve the activate method until setLocale fulfills it's promise it works also bundled. So all seems fine with the 0.5.1 release...

**Comment by tuath** [comment] 2016-04-07 12:07
Confirmed,  I grab the latest js and put in my jspm packages folder and seems to work.  Was waiting g for official build to report back.


Sent from Outlook Mobile






On Thu, Apr 7, 2016 at 1:49 AM -0700, "Tony Olsson" <notifications@github.com> wrote:





Seems to be working fine now with v0.5.1 :-)

---
