### ISSUE TITLE
setLocale will attempt to also load translation.json when custom namespaces have been configured

### ISSUE THREAD

**Issue by art0rz** [aurelia/i18n#80] opened 2016-03-15 13:48 UTC
I have configured aurelia-i18n to use a different namespace than `translation` and have set it to default. When I try to change the active locale by calling `setLocale`, it will load my namespace file and `translation.json`, while I believe it should only load the custom namespace file. I am using version `0.4.13`.

[Reproduce on Plunker](http://plnkr.co/edit/WkvDtx?p=preview).

**Comment by zewa666** [comment] 2016-03-15 14:03
hm thats quite interesting. I don't think it's caused by the plugin. Can you verify the same behavior with the v2 of aurelia-i18n?

**Comment by art0rz** [comment] 2016-03-16 09:13
@zewa666 where can I find v2/how do I install it?

**Comment by zewa666** [comment] 2016-03-16 15:38
@art0rz look at the end of this issue https://github.com/aurelia/i18n/issues/71

**Comment by art0rz** [comment] 2016-03-16 16:06
@zewa666 that doesn't seem to work at all, it just prints the keys, unless I've misconfigured it?

```
		.plugin('aurelia-i18n', (instance:I18N) =>
		{
			instance.setup({
				ns: 'global',
				defaultNS: 'global',
				resGetPath: 'data/locale/__lng__/__ns__.json',
				lng: 'en',
				attributes: ['t', 'i18n'],
				fallbackLng: 'en'
			});
		});```

Doesn't appear to be doing any XHR calls (neither translation.json nor global.json)

**Comment by zewa666** [comment] 2016-03-17 08:44
@art0rz yep, thats the old install, take a look at the updated plugin registration over here: https://github.com/aurelia/i18n/tree/update-i18next#how-to-install-this-plugin

**Comment by art0rz** [comment] 2016-03-17 10:23
Seems to work with v2. I do however need to specify the namespace when using it, even though it's default.

```html
<h2 t="[html]global:home.tagline"></h2>
```

But switching languages works correctly, it loads `global` for every language I switch to.

```javascript
.plugin('aurelia-i18n', (instance:I18N) => {
	instance.i18next.use(XHR);
	instance.setup({
		backend: { loadPath: 'data/locale/{{lng}}/{{ns}}.json', },
		ns: ['main'],
		defaultNs: 'main',
		lng: 'en',
		attributes: ['t', 'i18n'],
		fallbackLng: 'en',
		debug: false
	});
});
```

**Comment by zewa666** [comment] 2016-03-17 10:44
ok. Well the redefinition was also necessary in previous versions and seems to be by design from i18next. So that said, it's good to know that it works with the new version and thus will be fixed when we update.

Thanks for the investigation @art0rz

**Closed** 2016-04-04 07:41 UTC
Labels: wontfix
