### ISSUE TITLE
Error injecting i18n unit test

### ISSUE THREAD

**Issue by ggrimbert** [aurelia/i18n#48] opened 2015-12-21 14:35 UTC
Hi,

I'm experiencing issues while using aurelia-i18n with unit tests.
I'm injecting I18N in my classes and the test fails at : 

var i18nName = loader.normalizeSync('aurelia-i18n'); from file i18n.js
When the app pass this line, loader is undefined, as all parameters of the constructor.

![image](https://cloud.githubusercontent.com/assets/15869188/11932795/366d3da6-a7f8-11e5-8061-c8a0e1d13619.png)

this is how I launch my test : 
![image](https://cloud.githubusercontent.com/assets/15869188/11932802/4347a3ea-a7f8-11e5-9f7c-e51a4d7d9548.png)

My class TranslationService injects i18n

If i remove I18N from my class, my tests that do not use it don't fail.

**Comment by zewa666** [comment] 2015-12-22 07:29
Without the actual code I may just guess so could you create a plunker so we can test your issue?

**Comment by ggrimbert** [comment] 2015-12-22 08:19
Sorry but plunker is down, so i can just copy/paste my code : 

```javascript
import { inject } from 'aurelia-framework';
import {I18N} from 'aurelia-i18n';
import {EventAggregator} from 'aurelia-event-aggregator';


@inject(I18N,EventAggregator)
/** Gère la connexion, en singleton */
export class TraductionService {

	constructor(i18nSrv,msgService,element){
		this.i18n = i18nSrv;
		this.messenger = msgService;
		
		this.messenger.subscribe('connection', isCo => {
			if(isCo) {
				this.onConnection();
			}
		});
	}
}
```

With this code, and the unit test posted above, I launch "karma start" and get the following result in command line : 

```
Error: Error invoking I18N. Check the inner error for details.
        ------------------------------------------------
        inner error: TypeError: Cannot read property 'normalizeSync' of undefined
            at new I18N (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-i18n@0.4.4/i18n.js:24:28)
            at Object.invoke (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:334:14)
            at InvocationHandler.invoke (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:309:168)
            at Container.invoke (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:557:25)
            at StrategyResolver.get (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:145:37)
            at Container.get (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:488:41)
            at Object.invoke (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:344:33)
            at InvocationHandler.invoke (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:309:168)
            at Container.invoke (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:557:25)
            at StrategyResolver.get (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:145:37)
            at StrategyResolver.get (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:145:37)
            at Container.get (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:488:41)
            at Object.invoke (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:344:33)
            at InvocationHandler.invoke (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:309:168)
            at Container.invoke (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:557:25)
            at StrategyResolver.get (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:145:37)
            at Container.get (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:488:41)
            at new AggregateError (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-pal@1.0.0-beta.1.0.1/aurelia-pal.js:20:13)
            at Container.invoke (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:559:15)
            at TemplatingEngine.createControllerForUnitTest (/home/ggrimbert/edevelo/local/Aurelia/webapptest/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:4031:39)
```

**Comment by ggrimbert** [comment] 2015-12-29 10:19
Hi,

Are you working on this, or do you need other informations ?

**Comment by EisenbergEffect** [comment] 2015-12-29 14:25
@zewa666 Ping

**Comment by ggrimbert** [comment] 2015-12-29 14:51
I come with some news, after investigating and debugging a lot, I found that inside the aurelia-dependency-injector, an invoke method is called based on the injects of the class. However, I18N has no inject, so the invoke method is called without parameters, causing the problem I have. 

Example with I18N : 

![image](https://cloud.githubusercontent.com/assets/15869188/12036155/9fed40e0-ae43-11e5-8e1f-b3c7e2262941.png)


Example with any other class : 
![image](https://cloud.githubusercontent.com/assets/15869188/12036163/b78e3182-ae43-11e5-831f-5d9a7d7abf96.png)

The problem appears only with unit tests because in "classic mode", I come from aurelia-i18n configure method that creates a new instance of I18N.

**Comment by EisenbergEffect** [comment] 2015-12-29 15:28
@zewa666 This should be an easy fix. Can we address this? Also, is there some particular reason that a factory needs to be used?

**Comment by zewa666** [comment] 2016-01-04 17:28
@ggrimbert I still do not see a issue. I guess the way you've setup your unit tests may be wrong. Here is how I'd do it.

```
// file traduction-service.js in src folder
import { inject } from 'aurelia-framework';
import {I18N} from 'aurelia-i18n';
import {EventAggregator} from 'aurelia-event-aggregator';


@inject(I18N,EventAggregator)
/** Gère la connexion, en singleton */
export class TraductionService {

  constructor(i18nSrv,msgService,element){
    this.i18n = i18nSrv;
    this.messenger = msgService;

    this.messenger.subscribe('connection', isCo => {
      if(isCo) {
        this.onConnection();
      }
    });
  }
}
```

and here the unit test

```
import {I18N} from 'aurelia-i18n';
import {EventAggregator} from 'aurelia-event-aggregator';
import {Container} from 'aurelia-dependency-injection';
import {TemplatingEngine} from 'aurelia-framework';
import {initialize} from 'aurelia-pal-browser';
import {TraductionService} from '../../src/traduction-service';
import {DefaultLoader} from 'aurelia-loader-default';
import {BindingSignaler} from 'aurelia-templating-resources';

initialize();

describe("test", () => {

  let ts;
  let sut;

  beforeEach(() => {
    sut = new I18N(new EventAggregator(), new DefaultLoader(), new BindingSignaler());
    sut.setup({
      resStore: {},
      lng : 'en',
      getAsync : false,
      sendMissing : false,
      fallbackLng : 'en',
      debug : false
    });

    let container        = new Container();
    container.registerInstance(I18N, sut);
    let templatingEngine = container.get(TemplatingEngine);

    ts = templatingEngine.createViewModelForUnitTest(TraductionService);
  });

  fit("should", () => {
    console.log('tesT');
  });

});

```

**Comment by doktordirk** [comment] 2016-01-07 16:45
as it is i just had that error. happens simple when   
```javascript
 .plugin('aurelia-i18n', () => {})
```
isn't called. Imho "TypeError: Cannot read property 'normalizeSync' of undefined" isn't the best error message for users forgetting initializing the plugin (with nothing!).

**Comment by EisenbergEffect** [comment] 2016-01-07 16:51
@zewa666 Do you use Loader#normalizeSync internally? I hope not. If so, you and I need to coordinate to fix that **today**.

**Comment by zewa666** [comment] 2016-01-10 17:50
@doktordirk I think I remember you said that the last fix solved your issue is that right? @ggrimbert what about you, also using the previously posted test approach?

**Comment by doktordirk** [comment] 2016-01-10 17:53
yes. was fixed. tx

**Comment by ggrimbert** [comment] 2016-01-11 07:58
I haven't tried already, but this solution is not the best for me. I have created a service used in many classes, so if I want to use your solution, I have to implement it into all my unit tests

**Comment by zewa666** [comment] 2016-01-11 09:59
well I wouldn't know what to do else tbh. I18N is a service by itself, so in order to mock it or work with it you need to initialize it under test. You could also create a separate mock file which gets loaded automatically by karma to do the initial registration under test environment.

**Comment by zewa666** [comment] 2016-02-02 07:48
closing as the root cause was fixed

**Closed by zewa666** 2016-02-02 07:48 UTC
Labels: waiting for user feedback
