### ISSUE TITLE
ReferenceError: Can't find variable: IntlPolyfill

### ISSUE THREAD

**Issue by XuJinNet** [aurelia/i18n#149] opened 2016-08-30 01:47 UTC
I bundle the polyfill intl, get the error when running:
`ReferenceError: Can't find variable: IntlPolyfill global code`

``` json
{
  "name": "intl",
  "path": "../node_modules/intl/dist",
  "main": "Intl.complete"
}
```
- Framework Version:
  1.0.2
- aurelia-i18n Version:
  1.1.1
- intl Version:
  1.2.4
- Operating System:
  OSX 10.11.6
- Node Version:
  6.3.1
- NPM Version:
  3.10.3
- Aurelia-CLI:
  0.18.0
- Browser:
  Chrome 52.0 | Firefox 48.0 | Safari 9.1.2
- Language:
  ESNext

**Comment by XuJinNet** [comment] 2016-08-30 06:52
A temporary solution:
```json
"prepend": [
    "node_modules/bluebird/js/browser/bluebird.core.js",
     "node_modules/intl/dist/Intl.min.js",
     "node_modules/intl/locale-data/jsonp/zh.js",
     "scripts/require.js"
],
```

**Comment by zewa666** [comment] 2016-08-30 07:02
hmm have you tried using the Intl.min file as your `main`? Does this issue occur on all browsers or just Safari?

**Comment by XuJinNet** [comment] 2016-08-30 09:03
Yes, i tried using the Intl.min file as main, the same problem.
This issue occur on multiple browsers(Tested: Firefox, Chrome, Safari)

**Comment by XuJinNet** [comment] 2016-08-30 09:04
@zewa666  Yes, i tried using the Intl.min file as main, the same problem.
This issue occur on multiple browsers(Tested: Firefox, Chrome, Safari).

**Comment by zewa666** [comment] 2016-08-31 06:27
funny enough I can't reproduce the issue with the CLI.
Here's my aurelia.json
```
{
            "name": "intl",
            "path": "../node_modules/intl/dist",
            "main": "Intl.min"
          },
          {
            "name": "i18next",
            "path": "../node_modules/i18next/dist/umd",
            "main": "i18next"
          },
          {
            "name": "aurelia-i18n",
            "path": "../node_modules/aurelia-i18n/dist/amd",
            "main": "aurelia-i18n"
          },
          {
            "name": "i18next-xhr-backend",
            "path": "../node_modules/i18next-xhr-backend/dist/umd",
            "main": "i18nextXHRBackend"
          },
```

have you made sure you've installed the dependencies via npm install --save?
Otherwise could you zip up your solution and upload it somewhere so I can take a look?

**Comment by ielcoro** [comment] 2016-09-22 03:53
This occures only when trying to load locale data, either via intl.complete or manually loading provided jsonp locale data. 

Since [this commit ](https://github.com/andyearnshaw/Intl.js/commit/7bd583ba26523003f4fa2abd6efecb997007bf7e)in Intl, The locale data files expect the IntlPolyfill variable to be avaliable as global, [en.js](https://github.com/andyearnshaw/Intl.js/blob/master/locale-data/jsonp/en.js#L1), however, they have an [open issue with this change](https://github.com/andyearnshaw/Intl.js/issues/218), when Intl detects a module loader, it does not expose the IntlPolyfill global variables ([source](https://github.com/andyearnshaw/Intl.js/blob/master/dist/Intl.js#L4)), therefore the undefined error.

In it's current form, see [aurelia-i18n.js configure function](https://github.com/aurelia/i18n/blob/master/src/aurelia-i18n.js#L63), aurelia-i18n handles the creation of the Intl global variable after loading the polyfill, and as suggested in the referenced issue the suggested workaround is to create the IntlPolyfill variable to get locale data working. 

This is happening with the released 1.2.5 version

**Comment by zewa666** [comment] 2016-09-30 06:27
@ielcoro would you mind creating a PR for that? It'd be cool to finally get rid of those nasty loading issues.

**Comment by ielcoro** [comment] 2016-10-03 06:23
Sure! I have to review how to build the code locally first.

I expect to have the PR within this week.

**Comment by zewa666** [comment] 2016-10-03 09:33
Thanks. The easiest  way is to clone the repository and `gulp build` your changes. Now over in a local CLI App you install the aurelia-i18n dependency by referencing your local folder: `npm install /path-to-your-aurelia-i18n-root` and perform all the other setup tasks the same way as described in the readme.

As of now whenever you gulp build you'll work with the updated code (it might be needed to restart au serve though in order to rebundle the changes to the vendor bundle)

**Comment by zewa666** [comment] 2016-10-14 05:22
@ielcoro any update on this one?

**Comment by ielcoro** [comment] 2016-10-14 16:02
@zewa666 Sorry, it's has been a tought week at work closing three projects, one slipped the date.... Anyway, I will to work on this tomorrow, if it's ok to you.

**Comment by zewa666** [comment] 2016-10-14 16:57
Absolutely np, just wanted to ping you and see where we're at. Thx

**Comment by ielcoro** [comment] 2016-10-18 17:41
Well, that didn´t go as I expected...

I think we cannot fix the problem on aurelia's end. Intl either bundling Intl.complete or specific locale data, still throws the error.

In my analysis, we set up the intl instance too late (as we should, cause we are a module), and the locale data files start executing and call IntlPolyFill directly when the bundle is readed by the browser. I was trying to do something like the webpack example in the Intl polyfill on our end, when aurelia-i18n loads Intl here, however the locale data has already tried to locate de IntlPolyFill loaded.

I went through various loader configurations, trying to prevent locale data from executing until aurelia-i18n was loaded, but I was unable to get it right. 

The only thing I can think that would solve the problem is to wrap those locales inside a function or module, but I don't know how to do that in Require, I remember it can be done in Webpack. If anyone knows how to do this in require I can send a PR with the code. 

For the time being, until the issue in Intl is solved (probably changing the way they load json data), I think our best option is to put @XuJinNet workaround in the docs. I discarded other possible solutions, like including intl locale files modified in aurelia-i18n, that would create a maintenance nightmare.

**Comment by zewa666** [comment] 2016-11-03 06:56
So I'm still not entirely sure if that is something related fully to us, or due to the Polyfill itself. I think we should wait for [said issue](https://github.com/andyearnshaw/Intl.js/issues/218) to lay out a proper solution, until so we can either go with @XuJinNet's workaround or the one in [this comment](https://github.com/andyearnshaw/Intl.js/issues/218#issuecomment-242123177).

**Comment by Alexander-Taran** [comment] 2022-05-23 20:39
@bigopon 
Duplicate of https://github.com/aurelia/cli/issues/297

which was created later and closed

**Closed** 2022-05-24 04:57 UTC
Labels: bug, has-external-dependency
