### ISSUE TITLE
Support for Typescript

### ISSUE THREAD

**Issue by SorenMuller** [aurelia/i18n#27] opened 2015-10-20 11:31 UTC
It would be absolutely awesome, if support for Typescript were added.. :-)

**Comment by SorenMuller** [comment] 2015-11-02 14:25
Any idea when this issue will be adressed ??

**Comment by EisenbergEffect** [comment] 2015-11-02 16:01
In the next release....beta is coming in the next week or so. We are waiting on some dependency tooling updates which broke use...related to the Babel 6 update. Hang in there.

**Comment by nomack84** [comment] 2015-11-12 19:56
This is a duplicate of #8

**Closed** 2015-12-01 20:14 UTC
Labels: enhancement
