### ISSUE TITLE
Module ''i18next'' has no default export

### ISSUE THREAD

**Issue by Daviot** [aurelia/i18n#233] opened 2017-07-25 07:48 UTC
**I'm submitting a bug report**

* **Library Version:**
1.6.2

**Please tell us about your environment:**
* **Operating System:**
Linux ubuntu 16.04 LTS

* **Node Version:**
7.10.0

* **NPM Version:**
5.3.0

* **JSPM OR Webpack AND Version**
webpack 2.7.0

* **Browser:**
all

* **Language:**
TypeScript 2.4.2

**Current behavior:**
I will get the error:

> Module ''i18next'' has no default export.

In the file dist/aurelia-i18n.d.ts on line 2
`import i18next from 'i18next';`
which should be 
`import * as i18next from 'i18next';`

* **What is the motivation / use case for changing the behavior?**
I made this change multiple times in my local files, thanks for the help

**Comment by zewa666** [comment] 2017-07-26 18:15
closing as it's a duplicate of https://github.com/aurelia/i18n/pull/198

**Closed by zewa666** 2017-07-26 18:15 UTC
