### ISSUE TITLE
Position of t-params.bind in HTML code

### ISSUE THREAD

**Issue by steamonimo** [aurelia/i18n#65] opened 2016-02-08 13:14 UTC
It might be a coincidence but since the last update the replacement of variables with t-params.bind will only work with the correct order of t-params and t. Since HTML usually has no order in its attributes this might be the root for unexpected problems: 

This **will work**
```
<h3 t-params.bind="params" t="LogoutTitle">Are you done?</h3>
```
This **will fail**
```
<h3 t="LogoutTitle" t-params.bind="params">Are you done?</h3>
```

**Comment by Mordred** [comment] 2016-02-08 13:29
Maybe this commit? https://github.com/aurelia/i18n/commit/019fd7bd6b21f917f8e59b2adda81e5c5784d1e0

**Comment by zewa666** [comment] 2016-05-13 06:51
@steamonimo is this still an issue in the recent version? I'm not able to reproduce it

**Comment by EisenbergEffect** [comment] 2016-07-04 14:28
Closing since this can't be reproduced and seems to have been fixed in a more recent release.

**Closed by EisenbergEffect** 2016-07-04 14:28 UTC
Labels: waiting for user feedback
