### ISSUE TITLE
i18next-xhr-backend with typescript bug

### ISSUE THREAD

**Issue by olehleskiv** [aurelia/i18n#103] opened 2016-04-27 14:49 UTC
When using i18n with typescript  I has an error during compilation ` Module ''i18next-xhr-backend'' has no default export."`

I think that is because `i18next-xhr-backend` has no `i18next-xhr-backend.d.ts` file with def. types.

**Comment by zewa666** [comment] 2016-04-27 15:59
I'd really love if we could ask the author to provide a d.ts file in order to solve those issues further on. That would make the hole process much easier. In the meantime you'd have to provide your custom typings.

Take a look here https://github.com/aurelia/i18n/issues/89

**Comment by andrewMuntyan** [comment] 2016-04-30 09:16
can You look at https://github.com/aurelia/i18n/pull/106 ?

**Comment by krostkowski** [comment] 2016-05-13 11:49
There's another issue with typescript. When using `import Backend from 'i18next-xhr-backend'; ` according to readme, Backend is undefined. 
ES6 import is transpiled to AMD `instance.i18next.use(i18next_xhr_backend_1.default);`, while there is no default in exported function (constructor). 
`import * as Backend from 'i18next-xhr-backend';\ works.

**Comment by andrewMuntyan** [comment] 2016-05-13 16:04
@krostkowski You should use 
``` javascript
import * as Backend from 'i18next-xhr-backend';
```
it would be great if you will make a PR with fix about using `'i18next-xhr-backend'` with TS added to readme.

**Comment by krostkowski** [comment] 2016-05-14 08:47
@andrewMuntyan Done in #110

**Comment by zewa666** [comment] 2016-05-20 06:10
[Here's](https://github.com/aurelia/i18n/issues/112) a controversial issue proposing the original import Backend from ...syntax. So can I ask you guys to figure out why it does work that way for one TS user and not the other one?

**Comment by krostkowski** [comment] 2016-05-20 07:36
In my case I'm using typescript skeleton with gulp-tsb transpiler.
When I have
```
import Backend from 'i18next-xhr-backend
```
in my main.ts, it's transpiled to 
```
define(["require", "exports", 'aurelia-framework', 'i18next-xhr-backend',.... ], function (require, exports, aurelia_framework_1, i18next_xhr_backend_1...){
...
instance.i18next.use(i18next_xhr_backend_1.default);
...
```
i18next_xhr_backend_1 is a function:
```
function Backend(services) {
    var options = arguments.length <= 1 || arguments[1] === undefined ? {} : arguments[1];
    _classCallCheck(this, Backend);
    this.init(services, options);
    this.t…
}
```
It's a function from jspm_packages\npm\i18next-xhr-backend@0.5.4\dist\commonjs\index.js so it doesn't have a 'default' property.

When I change 'import Backend from `i18next-xhr-backend` to `import * as Backend from 'i18next-xhr-backend`; I get in my main.js:
```
instance.i18next.use(Backend);
```
and it works then.

**Comment by zewa666** [comment] 2016-05-20 08:11
@Souldrinker what do you see when looking at @krostkowski 's approach?

**Comment by Souldrinker** [comment] 2016-05-20 08:37
It might differ depending on how you transpile your TypeScript. It seems @krostkowski are transpiling TS->ES5 (AMD) while I'm transpiling TS->ES6->SystemJS (using Babel runtime).

In both cases ```import Backend from "i18next-xhr-backend";``` and ```import * as Backend from "i18next-xhr-backend";``` I get the same import as in TypeScript in my .js file (ES6).

But in the first case (which works) I get the following setters in the js!transpiled:
```
    return {
        setters: [function (_babelRuntimeCoreJsPromise) {
            _Promise = _babelRuntimeCoreJsPromise["default"];
        }, function (_babelRuntimeRegenerator) {
            _regeneratorRuntime = _babelRuntimeRegenerator["default"];
        }, function (_commonCookieHelper) {
            CookieHelper = _commonCookieHelper.CookieHelper;
        }, function (_aureliaFetchClient) {
            HttpClient = _aureliaFetchClient.HttpClient;
        }, function (_whatwgFetch) {}, function (_i18nextXhrBackend) {
            Backend = _i18nextXhrBackend["default"];
        }, function (_commonArrayAugmenter) {}],
        execute: function () {
```
...while if I use the second approach (that the docs suggest for TS users) the Backend row changes to ```Backend = _i18nextXhrBackend;``` that is without the default part and stuff and the app won't start, but rather outputs this: ```this.backend[c] is not a function```

**Comment by krostkowski** [comment] 2016-05-20 10:39
I don't know where is the problem but today I had the same situation with importing jquery. According to examples I should use:
```
import $ from 'jquery';
```
Which I had to change to 
```
import * as $ from 'jquery';
```
to work.

**Comment by zewa666** [comment] 2016-05-20 11:02
do you have all the typings installed @krostkowski?

**Comment by Souldrinker** [comment] 2016-05-20 11:06
I still think it's a ES6+Babel vs ES5 issue. I'm working on two different projects. One with TS->ES6+BabelRuntime where I have to import it as ```import Backend from "i18next-xhr-backend";``` and another where I do TS->ES5(AMD) where I have to import it as ```import * as Backend from "i18next-xhr-backend";```. Both projects use the same d.ts file:

```
declare module "i18next-xhr-backend" {
    var xhr;
    export default xhr;
}
```

**Comment by Souldrinker** [comment] 2016-05-20 11:13
I found something that sounds like the cause of this confusion that supports my theory: http://stackoverflow.com/questions/29596714/new-es6-syntax-for-importing-commonjs-amd-modules-i-e-import-foo-require

2016 update: The TypeScript compiler at some point started allowing import * as foo from 'legacy-module-foo' to get the default import of a legacy module in certain circumstances. This is a violation of the ES6 specification (§15.2.1.16, “The value "*" indicates that the import request is for the target module’s namespace object.”).

When legacy modules you import in this manner are updated to ES6 modules, the “default” imports for those modules will stop working (because ```* as foo``` imports are supposed to be importing namespace objects), which may be extremely confusing if you don’t know that doing this is a TypeScript/SystemJS hack. It is also possible that a future TypeScript realignment to the ES specification will cause them to break.

As such, you should probably prefer to continue to use the legacy import syntax described above to load legacy modules to avoid confusing yourself and other developers working on your code about how ES6 namespace imports work, and to avoid confusing breaking changes.

**Comment by EisenbergEffect** [comment] 2016-07-06 02:42
@zewa666 Status?

**Comment by Souldrinker** [comment] 2016-07-06 07:59
Well, this whole thing seems a bit confusing. We have a VS2015 solution using TypeScript 1.8 -> ES6 + Babel Runtime (to ES5) and the code in our main.ts is importing the xhr backend like this: ```import Backend from "i18next-xhr-backend";``` and using it in the plugin settings as ```instance.i18next.use(Backend);```.

We tried transpiling it on three different computers. Mine (that according to the About Visual Studio dialog) is running VS2015 Update 3 of VS and TypeScript 1.8.34.0 and a colleague that is using VS2015 Update 2 and TypeScript 1.8.30 is getting the above emitted as ES6 javascript the same as in TypeScript:
```
import Backend from "i18next-xhr-backend";
...
instance.i18next.use(Backend);
```

But the third guy that according to VS2015 was is using TypeScript 1.8.6.0 (and previously have been able to run the app) got it emitted as:
```
const i18next_xhr_backend_1 = require("i18next-xhr-backend");
...
instance.i18next.use(i18next_xhr_backend_1.default);
```

He then tried changing the import in the ts file to ```import * as Backend from "i18next-xhr-backend";``` and then it got emitted as:
```
const Backend = require("i18next-xhr-backend");
...
instance.i18next.use(Backend);

```
...which seemed more correct, but still different from our emitted code.

We then looked in our respective project properties dialog under the "TypeScript Build" sections and noticed that the guy that got it different also had ECMAScript version set to ECMAScript 6, but had module system "None" while we who got ES6 modules emitted had "ES 2015" selected there (shouldn't that have been saved in the project file that we all got the same from TFS?).

He then changed to "ES 2015" and then he got the same ES6 modules as the rest of us. But when I tried to change to None or he changed back to None the JavaScript still gets emitted with ES6 modules, so we're very confused why he suddenly started to get requires rather than imports. And even though the code used "requires" it didn't look like ES5 code since there where const's and "fat arrows" in his emitted code.

Hopefully this will get more consistent with TypeScript 2.0 when we hopefully will be able to target ES5 directly without babel (with async/await), but maybe stuff will still be emitted differently for those who ignores IE users and target ES6 anyway?

**Comment by EisenbergEffect** [comment] 2016-07-06 13:19
Closing this since it seems like a configuration issue.

**Closed by EisenbergEffect** 2016-07-06 13:19 UTC

**Comment by Souldrinker** [comment] 2016-07-06 14:08
Well, my last post might have been a configuration issue, but there still seems to be some inconsistency regarding point 7 in the aurelia-i18n readme at least with TypeScript 1.8 where it says:
```
import Backend from 'i18next-xhr-backend'; // <-- your previously installed backend plugin

// if you use TypeScript
// import * as Backend from 'i18next-xhr-backend';
```

This suggestion is valid if you target ES5, but if you target ES6 you should still do it the uncommented way if I got things right (at least it is like that for my projects targeting different ES versions), but hopefully this will get resolved so it behaves consistent in TypeScript 2.0 no matter what ES version you target.

**Comment by EisenbergEffect** [comment] 2016-07-06 14:10
@Souldrinker Ah, gotcha. Would you mind submitting a PR to the readme to just add that as a note?

**Comment by Souldrinker** [comment] 2016-07-06 14:41
I'm mostly working with TFS here and just fetch stuff from github and are not really sure how to do PR's (I think I've only done it once like a year ago) and will soon leave for the day.

But maybe slightly changing the text to something like this might help:
```
import Backend from 'i18next-xhr-backend'; // <-- your previously installed backend plugin

// if you use TypeScript and target ES5 you might need to import it like this instead
// import * as Backend from 'i18next-xhr-backend';
```

But the above is regarding the second issue @krostkowski mentioned.

The original issue could probably be considered fixed since the readme in step 8 explains how to get the d.ts files from the docs folder of aurelia-i18n.

**Comment by Souldrinker** [comment] 2016-07-06 17:21
Ok, that was simple enough ;-) I did the small change to the comment here: https://github.com/aurelia/i18n/pull/126. Not sure if there is a nicer way to link it to this issue?
